### PR TITLE
Initial 2.0

### LINKED ISSUE #1: discard file types option
For remove unmatched sources
```
{
  types: ['ttf', 'woff', 'svg']
}
```

### PR DESCRIPTION
**Pull request by TrySound**
fix #1

### CODE REVIEW

**Comment by ben-eb** [comment]
Great! No css-list? :wink:

**Comment by TrySound** [comment]
@ben-eb Maybe after rewriting.

**Comment by TrySound** [comment]
@ben-eb Or you think better use it now?

**Comment by TrySound** [comment]
Noop, in this case after rewriting :))

**Comment by ben-eb** [comment]
@TrySound It's fine, if you want to wait for a rewrite. :smile:

I'll update the docs and publish. Thanks! :+1:

**Comment by TrySound** [comment]
@ben-eb You're welcome!

**Pull request merged**
