### PR TITLE
Added font weight and style filter

### PR DESCRIPTION
**Pull request by TrySound**

### CODE REVIEW

**Comment by ben-eb** [comment]
Released as `2.1.0`, thanks. :+1:

**Comment by TrySound** [comment]
@ben-eb Is code normal?

**Comment by ben-eb** [comment]
I [tidied it up](https://github.com/ben-eb/postcss-discard-font-face/commit/5decae31ac8b10f8653097b9551e8f0539156714) a bit.

**Comment by TrySound** [comment]
@ben-eb Cool! Thanks!

**Pull request merged**
